sudo: false

language: node_js

node_js:
  - 6.11.5 # Cloud Functions Runtime (Used for firebase-functions)
  - 8
  - 9

notifications:
  # Only send notifications when travis status changes
  email:
    on_failure: change
    on_success: change

addons:
  code_climate:
    repo_token: $CODE_CLIMATE

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - next

script:
  - npm run lint
  - npm run test:cov

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    node: '9'
    branch: 'master'

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run codecov
