language: node_js

node_js:
  - "6"

branches:
  only:
    - master

script:
  - npm run lint:fix
  - npm run test:cov

cache:
  directories:
  - $HOME/.npm

addons:
  code_climate:
    repo_token: $CODE_CLIMATE

before_install:
  - "npm install react firebase lodash redux react-redux"

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/*/lcov.info
  - bash <(curl -s https://codecov.io/bash)
