sudo: false

language: node_js

node_js:
  - 6.14.0 # Maintenance LTS (Used by Cloud Functions Runtime)
  - 8 # Active LTS
  - 9
  - 10 # Current release

notifications:
  # Only send notifications when travis status changes
  email:
    on_failure: change
    on_success: change

addons:
  code_climate:
    repo_token: $CODE_CLIMATE

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - next

script:
  - npm run lint
  - npm run test:cov

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      node: '10'
      branch: 'master'
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    tag: next
    on:
      node: '10'
      branch: 'next'

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run codecov
